### ISSUE TITLE
Add timezone flag for Docker and Apptainer

### ISSUE THREAD

**Issue by complexbrains** [courtois-neuromod/cneuromax#248]
Docker or Apptainer's timezone is set to UTC or local time during built as default. According to the various resources in order to change it one should add 

`--env TZ=your_local_time_zone`

flag to the execution of the image run. 

However, I couldn't reproduce its use at my end for these two containers; hence I excluded the adding a note regarding the use of this flag.

So it awaits reproducing, hence adding back into the docs!

**Comment by maximilienleclei** [comment]
looks like apptainer doesn't need the flag to get the right time

**Comment by maximilienleclei** [comment]
fixed in https://github.com/courtois-neuromod/cneuromax/pull/246
