### ISSUE TITLE
use self-explanatory names in the folder structure

### ISSUE THREAD

**Issue by lunebellec** [courtois-neuromod/cneuromax#30]
In particular: 
ne -> neuroevolution 
dl -> deeplearning (or gradient_descent)? 
litmodule -> lightning_module

This will reduce the needs for documentation.
Good libraries have good variable and folder names. 
In the age of smart auto-complete, there is simply no excuse for cryptic acronyms.

**Comment by maximilienleclei** [comment]
agree for dl/ne, will change
agree but ultimately disagree for litmodule, this is the widespread naming convention

**Comment by lunebellec** [comment]
Alright, if it's commonly used let's stick with it

**Comment by maximilienleclei** [comment]
#46
