### ISSUE TITLE
Adding introductory explanation in readme and doc

### ISSUE THREAD

**Issue by complexbrains** [courtois-neuromod/cneuromax#40]
I know this is not an emergency but eventually, at some point it would be nice to add the main introductory explanation in both readme and doc websites regarding

-  what the tool is about, 
- why to use it
- who are the targeted users
- and how to contribute (a.k.a [contribution guidelines as in niprep](https://www.nipreps.org/community/CONTRIBUTING/) or as in [Mozilla's](https://www.mozilla.org/en-US/about/governance/policies/participation/)
- and a [Code of Conduct](https://www.nipreps.org/community/CODE_OF_CONDUCT/)

**Comment by maximilienleclei** [comment]
https://github.com/courtois-neuromod/cneuromax/pull/64 -> https://courtois-neuromod.github.io/cneuromax/index.html
